sudo: required
services:
- docker
before_install:
- docker build --tag tensortrade -f docker/Dockerfile.tests .
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
before_script:
- bash test_mypy.sh
script:
- echo "SCRIPT SECTION"
