sudo: required
services:
- docker
language: python
python:
- '3.5'
install:
- pip install -e .[tf,tensorforce,ccxt,fbm,tests]
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
